version: '3.1'
services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: demo_crud
    ports:
      - "3306:3306"
    volumes:
      - $HOME/Desktop/MySQL-Snippets/demo_crud.sql:/demo_crud.sql